languageCode = "vi"
languageName = "Tiếng Việt"
displayName = "VN"
isoCode = "vn"
weight = 1
rtl = false

title = "IndieCrew Studio"
logo = "img/logo.png"
description = "IndieCrew Studio"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "IndieCrew Studio"
  image = "img/avatar.png"
  headline = "Vài dòng link tinh"
  bio = "A little bit about you"
